# This script requires setting up your 'Personal access tokens' from github
# in your travis build setting as 'GH_TOKEN' and running travis encrypt
# API authentication from travis
dist: bionic

language: python

python:
  - "3.8.5"

#cache:
#  - pip

env:
  global:
    - GIT_NAME: "Spirillen"
    - GIT_EMAIL: 44526987+spirillen@users.noreply.github.com
    - TRAVIS_REPO_SLUG: Import-External-Sources/Forbrukertilsynet-falske-nettbutikker
    - GIT_BRANCH: master
    - TZ: UTC
    - PYFUNCEBLE_CONFIG_DIR: ${TRAVIS_BUILD_DIR}/dev-tools/
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble
    - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - PYFUNCEBLE_OUTPUT_LOCATION: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - PYFUNCEBLE_AUTO_CONFIGURATION: yes
    - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
    - PYFUNCEBLE_DB_HOST="${DB_HOST}"
    - PYFUNCEBLE_DB_NAME="${DB_NAME}"
    - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
    - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
    - PYFUNCEBLE_DB_PORT="${DB_PORT}"
    
addons:
  apt:
    update: true
    packages:
    - dos2unix
    - msttcorefonts

install:
  - pip3 install --upgrade pip
  - pip3 install PyFunceble-dev
  #- pip3 install ultimate-hosts-blacklist-whitelist
  - pip3 install ultimate-hosts-blacklist-whitelist

git:
  depth: 5

matrix:
  fast_finish: true

sudo: required

script:
  # We put both in same statement so that if one fails the whole test result will fail.
  - bash dev-tools/PrepareData.sh && bash dev-tools/DataTesting.sh
