# This script requires setting up your 'Personal access tokens' from github
# in your travis build setting as 'GH_TOKEN' and running travis encrypt
# API authentication from travis
language: python
os: linux
dist: bionic

python:
  - "3.8.5"

env:
  global:
    - GIT_NAME: "Spirillen"
    - GIT_EMAIL: 44526987+spirillen@users.noreply.github.com
    - TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}
    - GIT_BRANCH: ${TRAVIS_BRANCH}
    - TZ: UTC
    - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/.pyfunceble/" #${TRAVIS_BUILD_DIR}/dev-tools/
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble
    - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - PYFUNCEBLE_OUTPUT_LOCATION: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - PYFUNCEBLE_AUTO_CONFIGURATION: yes
    - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
    - PYFUNCEBLE_DB_HOST="${DB_HOST}"
    - PYFUNCEBLE_DB_NAME="${DB_NAME}"
    - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
    - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
    - PYFUNCEBLE_DB_PORT="${DB_PORT}"
    
addons:
  apt:
    update: true
    packages:
    - dos2unix
    - msttcorefonts
    - lsof

install:
  - pip3 install --upgrade pip
  - pip3 install  --no-cache-dir -U wheel pyfunceble-dev ultimate-hosts-blacklist-whitelist-dev

git:
  depth: 5

matrix:
  fast_finish: true

sudo: required

script:
  # We put both in same statement so that if one fails the whole test result will fail.
  - bash dev-tools/PrepareData.sh && bash dev-tools/DataTesting.sh
